Repository Team-Blitz-Steady/steady-server, pull requests merged in 2023-12, with the labels that each got.

#178 [6차 스프린트 - Steady] 연락 수단 전체 공개
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
Labels: 🧚 Refactor, size/XS

#186 [스테디] 스테디 좋아요 낙관적 락 적용
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/service/SteadyLikeService.java
  src/main/java/dev/steady/steady/service/SteadyService.java
Labels: size/S

#191 [신청서] 같은 스터디에 중복으로 신청서 제출 및 작성자 제출 검증 로직
  build.gradle
  src/main/java/dev/steady/application/domain/repository/ApplicationRepository.java
  src/main/java/dev/steady/application/exception/ApplicationErrorCode.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/main/java/dev/steady/global/advice/GlobalExceptionHandler.java
  src/main/java/dev/steady/global/exception/DuplicateException.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
Labels: size/L

#182 Instancio를 활용한 Fixture 생성
  build.gradle
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/repository/SteadyStackRepository.java
  src/main/java/dev/steady/steady/dto/request/SteadyCreateRequest.java
  src/main/java/dev/steady/steady/dto/request/SteadyUpdateRequest.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/resources/application.yml
  src/test/java/dev/steady/application/domain/repository/ApplicationRepositoryTest.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/auth/service/AccountServiceTest.java
  src/test/java/dev/steady/notification/service/NotificationServiceTest.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/fixture/SteadyFixturesV2.java
  src/test/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImplTest.java
  src/test/java/dev/steady/steady/service/SteadyLikeServiceTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/template/domain/TemplateTest.java
  src/test/java/dev/steady/template/domain/repository/TemplateRepositoryTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
  src/test/java/dev/steady/user/controller/PositionControllerTest.java
  src/test/java/dev/steady/user/controller/StackControllerTest.java
  src/test/java/dev/steady/user/controller/UserControllerTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
  src/test/java/dev/steady/user/fixture/UserFixturesV2.java
  src/test/java/dev/steady/user/service/PositionServiceTest.java
  src/test/java/dev/steady/user/service/StackServiceTest.java
  src/test/java/dev/steady/user/service/UserServiceTest.java
Labels: Test, ✏️ Feature, size/XXL

#192 Instancio를 활용한 Fixture 생성
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/dto/response/SteadyDto.java
  src/main/resources/application.yml
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/infrastructure/SteadyQueryRepositoryImplTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
Labels: Test, ✏️ Feature, 🧚 Refactor, size/XL
