Repository Team-Blitz-Steady/steady-server, pull requests merged in 2023-10, with the labels that each got.

#16 :white_check_mark: 스웨거 + Rest Docs 환경 적용
  .gitignore
  build.gradle
  src/main/resources/application.yml
  src/test/java/dev/steady/HealthControllerTest.java
Labels: ✏️ Feature, size/M

#20 [1차 스프린트 - Steady] 스테디 생성 PR 피드백 및 ERD 수정 반영
  src/main/java/dev/steady/HealthController.java
  src/main/java/dev/steady/applicationForm/domain/Answer.java
  src/main/java/dev/steady/applicationForm/domain/ApplicationFormStatus.java
  src/main/java/dev/steady/global/auth/AuthContext.java
  src/main/java/dev/steady/review/domain/Review.java
  src/main/java/dev/steady/review/domain/ReviewSticker.java
  src/main/java/dev/steady/review/domain/Sticker.java
  src/main/java/dev/steady/steady/application/SteadyService.java
  src/main/java/dev/steady/steady/domain/ParticipantRole.java
  src/main/java/dev/steady/steady/domain/Position.java
  src/main/java/dev/steady/steady/domain/Promotion.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/SteadyLike.java
  src/main/java/dev/steady/steady/domain/SteadyMode.java
  src/main/java/dev/steady/steady/domain/SteadyQuestion.java
  src/main/java/dev/steady/steady/domain/SteadyStatus.java
  src/main/java/dev/steady/steady/domain/SteadyType.java
  src/main/java/dev/steady/steady/domain/repository/SteadyQuestionRepository.java
  src/main/java/dev/steady/steady/domain/repository/SteadyRepository.java
  src/main/java/dev/steady/steady/dto/request/SteadyCreateRequest.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/java/dev/steady/steadyForm/domain/Question.java
  src/main/java/dev/steady/steadyForm/infrastructure/SteadyFormRepository.java
  src/test/java/dev/steady/HealthControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/presentation/SteadyControllerTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/steadyForm/fixture/SteadyFormFixtures.java
Labels: ✏️ Feature, 🧚 Refactor, size/L

#21 템플릿 양식 저장 API 기능 추가
  src/main/java/dev/steady/applicationForm/domain/Answer.java
  src/main/java/dev/steady/template/domain/Question.java
  src/main/java/dev/steady/template/domain/Template.java
  src/main/java/dev/steady/template/domain/repository/QuestionRepository.java
  src/main/java/dev/steady/template/domain/repository/TemplateRepository.java
  src/main/java/dev/steady/template/dto/request/CreateTemplateRequest.java
  src/main/java/dev/steady/template/presentation/TemplateController.java
  src/main/java/dev/steady/template/service/TemplateService.java
  src/main/java/dev/steady/user/infrastructure/UserRepository.java
  src/main/resources/application.yml
  src/test/java/dev/steady/common/config/ControllerTestConfig.java
  src/test/java/dev/steady/steady/presentation/SteadyControllerTest.java
  src/test/java/dev/steady/template/presentation/TemplateControllerTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
  src/test/resources/application.yml
Labels: size/L

#23 [템플릿] - 템플릿 양식 목록 조회 개발
  src/main/java/dev/steady/steady/domain/SteadyQuestion.java
  src/main/java/dev/steady/template/domain/Question.java
  src/main/java/dev/steady/template/domain/Template.java
  src/main/java/dev/steady/template/domain/repository/TemplateRepository.java
  src/main/java/dev/steady/template/dto/request/CreateTemplateRequest.java
  src/main/java/dev/steady/template/dto/resonse/TemplateResponse.java
  src/main/java/dev/steady/template/dto/resonse/TemplateResponses.java
  src/main/java/dev/steady/template/presentation/TemplateController.java
  src/main/java/dev/steady/template/service/TemplateService.java
  src/main/resources/application.yml
  src/test/java/dev/steady/global/auth/AuthFixture.java
  src/test/java/dev/steady/global/config/ControllerTestConfig.java
  src/test/java/dev/steady/steady/presentation/SteadyControllerTest.java
  src/test/java/dev/steady/template/domain/repository/TemplateRepositoryTest.java
  src/test/java/dev/steady/template/fixture/TemplateFixture.java
  src/test/java/dev/steady/template/presentation/TemplateControllerTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
Labels: size/L

#26 [템플릿] - 템플릿 양식 상세 조회
  src/main/java/dev/steady/global/entity/BaseEntity.java
  src/main/java/dev/steady/steady/domain/SteadyQuestion.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/java/dev/steady/template/domain/Questions.java
  src/main/java/dev/steady/template/domain/Template.java
  src/main/java/dev/steady/template/dto/resonse/TemplateDetailResponse.java
  src/main/java/dev/steady/template/presentation/TemplateController.java
  src/main/java/dev/steady/template/service/TemplateService.java
  src/main/java/dev/steady/user/domain/User.java
  src/main/java/dev/steady/user/infrastructure/UserRepository.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/template/domain/TemplateTest.java
  src/test/java/dev/steady/template/presentation/TemplateControllerTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
Labels: size/L

#30 [1차 스프린트 - Steady] 스테디 상세 조회
  src/main/java/dev/steady/application/domain/Application.java
  src/main/java/dev/steady/application/domain/repository/ApplicationRepository.java
  src/main/java/dev/steady/steady/domain/Participants.java
  src/main/java/dev/steady/steady/dto/response/LeaderResponse.java
  src/main/java/dev/steady/steady/dto/response/ParticipantResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadyQuestionResponse.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: ✏️ Feature, size/L

#35 [템플릿] 템플릿 양식 업데이트 API 개발
  src/main/java/dev/steady/template/domain/Questions.java
  src/main/java/dev/steady/template/domain/Template.java
  src/main/java/dev/steady/template/dto/request/UpdateTemplateRequest.java
  src/main/java/dev/steady/template/presentation/TemplateController.java
  src/main/java/dev/steady/template/service/TemplateService.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
Labels: size/M

#34 [1차 스프린트 - User] KAKAO 소셜 로그인
  build.gradle
  src/main/java/dev/steady/auth/config/JwtProperties.java
  src/main/java/dev/steady/auth/config/KakaoOAuthProperties.java
  src/main/java/dev/steady/auth/domain/Account.java
  src/main/java/dev/steady/auth/domain/JwtProvider.java
  src/main/java/dev/steady/auth/domain/Platform.java
  src/main/java/dev/steady/auth/domain/repository/AccountRepository.java
  src/main/java/dev/steady/auth/dto/response/TokenResponse.java
  src/main/java/dev/steady/auth/exception/OAuthInvalidResponseException.java
  src/main/java/dev/steady/auth/oauth/client/KakaoOAuthClient.java
  src/main/java/dev/steady/auth/oauth/client/OAuthClient.java
  src/main/java/dev/steady/auth/oauth/domain/AuthCodeRequestUrlProvider.java
  src/main/java/dev/steady/auth/oauth/domain/KakaoAuthCodeRequestUrlProvider.java
  src/main/java/dev/steady/auth/oauth/dto/KakaoToken.java
  src/main/java/dev/steady/auth/oauth/dto/response/KakaoUserInfoResponse.java
  src/main/java/dev/steady/auth/oauth/dto/response/LogInResponse.java
  src/main/java/dev/steady/auth/oauth/dto/response/OAuthUserInfoResponse.java
  src/main/java/dev/steady/auth/oauth/service/AuthCodeRequestService.java
  src/main/java/dev/steady/auth/oauth/service/OAuthClientService.java
  src/main/java/dev/steady/auth/oauth/service/OAuthService.java
  src/main/java/dev/steady/auth/presentation/OAuthController.java
  src/main/java/dev/steady/global/auth/AuthorizedArgumentResolver.java
  src/main/java/dev/steady/global/config/PropertiesConfig.java
  src/main/java/dev/steady/global/config/RestTemplateConfig.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/java/dev/steady/template/service/TemplateService.java
  src/main/java/dev/steady/user/domain/Platform.java
  src/main/java/dev/steady/user/domain/repository/UserRepository.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/template/domain/repository/TemplateRepositoryTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
  src/test/resources/application.yml
Labels: ✏️ Feature, size/XL
