Repository Team-Blitz-Steady/steady-server, pull requests merged in 2023-11, with the labels that each got.

#41 [2차 스프린트 - Steady] 스테디 끌어올리기 기능 추가
  src/main/java/dev/steady/steady/domain/Promotion.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/SteadyStatus.java
  src/main/java/dev/steady/steady/domain/repository/SteadyRepository.java
  src/main/java/dev/steady/steady/dto/request/SteadyCreateRequest.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: Style, ✏️ Feature, 🧚 Refactor, size/L

#38 [Feat] 템플릿 양식 삭제 API 개발
  src/main/java/dev/steady/template/domain/repository/TemplateRepository.java
  src/main/java/dev/steady/template/presentation/TemplateController.java
  src/main/java/dev/steady/template/service/TemplateService.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
Labels: size/L

#45 [2차 스프린트 - Steady] 스테디 ERD 변경 사항 반영
  src/main/java/dev/steady/steady/domain/ScheduledPeriod.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/dto/request/SteadyCreateRequest.java
  src/main/java/dev/steady/steady/dto/request/SteadyUpdateRequest.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 🧚 Refactor, size/M

#46 [2차 스프린트 - Steady] 스테디 종료
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: ✏️ Feature, size/M

#47 [2차 스프린트 - Steady] 스테디 삭제 기능
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/repository/SteadyPositionRepository.java
  src/main/java/dev/steady/steady/domain/repository/SteadyQuestionRepository.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/resources/application.yml
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/resources/application.yml
Labels: Test, ✏️ Feature, 🧚 Refactor, size/L

#48 [2차 스프린트 - Application] 스터디 신청 요청을 받아 신청서 생성
  src/main/java/dev/steady/application/domain/Answer.java
  src/main/java/dev/steady/application/domain/Application.java
  src/main/java/dev/steady/application/domain/SurveyResult.java
  src/main/java/dev/steady/application/dto/request/SurveyResultRequest.java
  src/main/java/dev/steady/application/dto/response/CreateApplicationResponse.java
  src/main/java/dev/steady/application/presentation/ApplicationController.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/test/java/dev/steady/application/fixture/SurveyResultFixture.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/template/domain/repository/TemplateRepositoryTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
Labels: ✏️ Feature, size/L

#43 [1차 스프린트 - User] 기본 프로필 작성 기능 구현
  src/main/java/dev/steady/auth/domain/Account.java
  src/main/java/dev/steady/auth/service/AccountService.java
  src/main/java/dev/steady/user/domain/User.java
  src/main/java/dev/steady/user/domain/UserStack.java
  src/main/java/dev/steady/user/domain/repository/UserRepository.java
  src/main/java/dev/steady/user/domain/repository/UserStackRepository.java
  src/main/java/dev/steady/user/dto/request/UserCreateRequest.java
  src/main/java/dev/steady/user/presentation/UserController.java
  src/main/java/dev/steady/user/service/UserService.java
  src/test/java/dev/steady/auth/service/AccountServiceTest.java
  src/test/java/dev/steady/auth/service/Fixtures/AccountFixture.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/user/service/UserServiceTest.java
Labels: ✏️ Feature, size/L

#50 [1차 스프린트 - Application] 참여 신청서 목록 조회
  src/main/java/dev/steady/application/domain/Application.java
  src/main/java/dev/steady/application/domain/repository/ApplicationRepository.java
  src/main/java/dev/steady/application/dto/request/ApplicationPageRequest.java
  src/main/java/dev/steady/application/dto/response/ApplicationSummaryResponse.java
  src/main/java/dev/steady/application/presentation/ApplicationController.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/main/java/dev/steady/application/service/SliceResponse.java
  src/main/java/dev/steady/auth/domain/Platform.java
  src/main/java/dev/steady/auth/exception/OAuthInvalidResponseException.java
  src/main/java/dev/steady/auth/oauth/dto/KakaoToken.java
  src/main/java/dev/steady/global/auth/AuthorizedArgumentResolver.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/dto/response/SteadyQuestionResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadySearchResponse.java
  src/main/java/dev/steady/template/presentation/TemplateController.java
  src/main/java/dev/steady/template/service/TemplateService.java
  src/main/java/dev/steady/user/domain/User.java
  src/test/java/dev/steady/application/domain/repository/ApplicationRepositoryTest.java
  src/test/java/dev/steady/application/fixture/ApplicationFixture.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/auth/service/AccountServiceTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/template/domain/TemplateTest.java
  src/test/java/dev/steady/template/domain/repository/TemplateRepositoryTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
Labels: ✏️ Feature, size/L

#52 [1차 스프린트 - Application] 참여 신청서 상세 조회 기능 개발
  src/main/java/dev/steady/application/domain/Application.java
  src/main/java/dev/steady/application/domain/SurveyResults.java
  src/main/java/dev/steady/application/domain/repository/ApplicationRepository.java
  src/main/java/dev/steady/application/dto/response/ApplicationDetailResponse.java
  src/main/java/dev/steady/application/dto/response/SliceResponse.java
  src/main/java/dev/steady/application/dto/response/SurveyResultResponse.java
  src/main/java/dev/steady/application/presentation/ApplicationController.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
Labels: size/L

#54 [2차 스프린트 - 기능 수정] 신청서의 목록조회 로직 변경
  src/main/java/dev/steady/application/domain/repository/ApplicationRepository.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/test/java/dev/steady/application/domain/repository/ApplicationRepositoryTest.java
Labels: size/S

#56 [2차 스프린트 - 신청서] 신청서 상세조회 유효성검증 범위 변경
  src/main/java/dev/steady/application/domain/Application.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/java/dev/steady/user/domain/User.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/template/domain/TemplateTest.java
Labels: size/M

#60 [2차 스프린트 - Steady] 스테디 검색 및 필터링 기능 추가
  build.gradle
  src/main/java/dev/steady/application/presentation/ApplicationController.java
  src/main/java/dev/steady/global/config/QueryDslConfig.java
  src/main/java/dev/steady/steady/domain/ParticipantRole.java
  src/main/java/dev/steady/steady/domain/SteadyMode.java
  src/main/java/dev/steady/steady/domain/SteadyStatus.java
  src/main/java/dev/steady/steady/domain/repository/SteadyRepository.java
  src/main/java/dev/steady/steady/dto/SearchConditionDto.java
  src/main/java/dev/steady/steady/dto/request/SteadySearchRequest.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepository.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
  src/main/java/dev/steady/steady/infrastructure/util/DynamicQueryUtils.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/application/domain/repository/ApplicationRepositoryTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImplTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/template/domain/repository/TemplateRepositoryTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
Labels: Test, ✏️ Feature, 🧚 Refactor, size/L

#61 [1차 스프린트 - User] JWT 처리 #31
  src/main/java/dev/steady/auth/domain/Authentication.java
  src/main/java/dev/steady/auth/domain/JwtProvider.java
  src/main/java/dev/steady/auth/domain/JwtResolver.java
  src/main/java/dev/steady/auth/exception/JwtInvalidException.java
  src/main/java/dev/steady/auth/exception/OAuthInvalidResponseException.java
  src/main/java/dev/steady/global/auth/Auth.java
  src/main/java/dev/steady/global/auth/AuthContext.java
  src/main/java/dev/steady/global/auth/AuthorizedArgumentResolver.java
  src/main/java/dev/steady/global/auth/JwtAuthenticationInterceptor.java
  src/main/java/dev/steady/global/auth/UserInfo.java
  src/main/java/dev/steady/global/config/WebMvcConfig.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/test/java/dev/steady/auth/fixture/AccountFixture.java
  src/test/java/dev/steady/auth/service/AccountServiceTest.java
  src/test/java/dev/steady/global/auth/AuthFixture.java
Labels: ✏️ Feature, size/L

#63 [2차 스프린트 - Steady] 로그인 흐름에 따른 스테디 상세 조회 로직 리팩토링
  src/main/java/dev/steady/global/auth/AuthorizedArgumentResolver.java
  src/main/java/dev/steady/global/auth/UserInfo.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 🧚 Refactor, size/L

#65 [2차 스프린트 - Steady] 스테디 리팩토링
  src/main/java/dev/steady/steady/domain/SteadyPosition.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadyPositionResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadySearchResponse.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 🧚 Refactor, size/L

#70 [2차 스프린트 - Steady] 스테디 컨트롤러 테스트 및 문서화
  src/main/java/dev/steady/auth/domain/Account.java
  src/main/java/dev/steady/steady/domain/ScheduledPeriod.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/SteadyLike.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/presentation/SteadyController.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/java/dev/steady/user/domain/User.java
  src/main/java/dev/steady/user/domain/UserStack.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/presentation/SteadyControllerTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 📘 Documentation, ✏️ Feature, size/XL

#71 [2차 스프린트 - User] OAuth 컨트롤러 테스트 및 문서화
  src/main/java/dev/steady/auth/domain/Platform.java
  src/main/java/dev/steady/auth/oauth/domain/AuthCodeRequestUrlProvider.java
  src/main/java/dev/steady/auth/oauth/domain/KakaoAuthCodeRequestUrlProvider.java
  src/main/java/dev/steady/auth/oauth/service/AuthCodeRequestService.java
  src/main/java/dev/steady/auth/oauth/service/OAuthService.java
  src/main/java/dev/steady/auth/presentation/OAuthController.java
  src/main/java/dev/steady/global/auth/AuthorizedArgumentResolver.java
  src/main/java/dev/steady/global/auth/UserInfo.java
  src/test/java/dev/steady/auth/fixture/OAuthFixture.java
  src/test/java/dev/steady/auth/presentation/OAuthControllerTest.java
  src/test/java/dev/steady/global/config/ControllerTestConfig.java
  src/test/java/dev/steady/template/presentation/TemplateControllerTest.java
Labels: 📘 Documentation, Test, size/L

#73 [2차 스프린트 - User] User Controller 테스트
  src/main/java/dev/steady/auth/domain/JwtResolver.java
  src/main/java/dev/steady/auth/oauth/dto/response/KakaoUserInfoResponse.java
  src/main/java/dev/steady/auth/service/AccountService.java
  src/main/java/dev/steady/global/auth/AuthContext.java
  src/main/java/dev/steady/global/auth/Authentication.java
  src/main/java/dev/steady/global/auth/JwtAuthenticationInterceptor.java
  src/main/java/dev/steady/user/presentation/UserController.java
  src/test/java/dev/steady/auth/fixture/OAuthFixture.java
  src/test/java/dev/steady/auth/presentation/OAuthControllerTest.java
  src/test/java/dev/steady/global/config/ControllerTestConfig.java
  src/test/java/dev/steady/steady/presentation/SteadyControllerTest.java
  src/test/java/dev/steady/template/presentation/TemplateControllerTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
  src/test/java/dev/steady/user/presentation/UserControllerTest.java
Labels: 📘 Documentation, Test, size/L

#76 [2차 스프린트 - Application] 신청서 컨트롤러 테스트 및 문서화
  src/main/java/dev/steady/application/presentation/ApplicationController.java
  src/test/java/dev/steady/application/fixture/ApplicationFixture.java
  src/test/java/dev/steady/application/presentation/ApplicationControllerTest.java
  src/test/java/dev/steady/global/config/ControllerTestConfig.java
Labels: size/L

#78 [3차 스프린트 - Exception] 커스텀 예외 적용
  src/main/java/dev/steady/global/advice/GlobalExceptionHandler.java
  src/main/java/dev/steady/global/exception/AuthenticationException.java
  src/main/java/dev/steady/global/exception/BusinessException.java
  src/main/java/dev/steady/global/exception/ErrorCode.java
  src/main/java/dev/steady/global/exception/ForbiddenException.java
  src/main/java/dev/steady/global/exception/GlobalErrorCode.java
  src/main/java/dev/steady/global/exception/NotFoundException.java
  src/main/java/dev/steady/global/response/ErrorResponse.java
Labels: ✏️ Feature, size/L

#86 [3차 스프린트 - Logging] 로깅 적용
  src/main/java/dev/steady/global/config/HibernateConfig.java
  src/main/java/dev/steady/global/config/JpaConfig.java
  src/main/java/dev/steady/global/config/WebMvcConfig.java
  src/main/java/dev/steady/global/logging/MDCRequestHandlerCommentInterceptor.java
  src/main/java/dev/steady/global/logging/MdcLoggingInterceptor.java
  src/main/resources/info-appender.xml
  src/main/resources/logback.xml
  src/main/resources/warn-appender.xml
Labels: ✏️ Feature, size/L

#80 [3차 스프린트 - User] 닉네임 중복 검사 기능 Response DTO 적용
  src/main/java/dev/steady/user/controller/UserController.java
  src/main/java/dev/steady/user/dto/response/UserNicknameExistResponse.java
  src/main/java/dev/steady/user/service/UserService.java
  src/test/java/dev/steady/auth/presentation/OAuthControllerTest.java
  src/test/java/dev/steady/user/controller/UserControllerTest.java
Labels: 🧚 Refactor, size/M

#88 [3차 스프린트 - 테스트코드 리팩토링] 신청서, 템플릿 테스트 리팩토링
  src/test/java/dev/steady/application/controller/ApplicationControllerTest.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/template/controller/TemplateControllerTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
Labels: size/L

#90 [3차 스프린트 - 테스트코드 리팩토링] 신청서, 템플릿 커스텀 에외코드 적용
  src/main/java/dev/steady/application/domain/Application.java
  src/main/java/dev/steady/application/domain/repository/ApplicationRepository.java
  src/main/java/dev/steady/application/exception/ApplicationErrorCode.java
  src/main/java/dev/steady/global/exception/AuthenticationException.java
  src/main/java/dev/steady/global/exception/BusinessException.java
  src/main/java/dev/steady/global/exception/ForbiddenException.java
  src/main/java/dev/steady/global/exception/NotFoundException.java
  src/main/java/dev/steady/template/domain/Template.java
  src/main/java/dev/steady/template/domain/repository/TemplateRepository.java
  src/main/java/dev/steady/template/exception/TemplateErrorCode.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/template/domain/TemplateTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
Labels: size/L

#91 [3차 스프린트 - Steady] 스테디 예외 및 도메인 로직 리팩토링
  src/main/java/dev/steady/steady/domain/Participants.java
  src/main/java/dev/steady/steady/domain/Promotion.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/repository/SteadyRepository.java
  src/main/java/dev/steady/steady/dto/SearchConditionDto.java
  src/main/java/dev/steady/steady/dto/response/LeaderResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/exception/InvalidStateException.java
  src/main/java/dev/steady/steady/exception/SteadyErrorCode.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/java/dev/steady/user/domain/repository/PositionRepository.java
  src/main/java/dev/steady/user/domain/repository/StackRepository.java
  src/main/java/dev/steady/user/exception/PositionErrorCode.java
  src/main/java/dev/steady/user/exception/StackErrorCode.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/domain/PromotionTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 🧚 Refactor, size/XL

#99 [3차 스프린트 - Steady] 스테디 참여자 조회
  src/main/java/dev/steady/steady/controller/SteadyController.java
  src/main/java/dev/steady/steady/dto/response/ParticipantResponse.java
  src/main/java/dev/steady/steady/dto/response/ParticipantsResponse.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 📘 Documentation, ✏️ Feature, size/L

#100 [3차 스프린트 - Steady] 스테디 질문 수정
  src/main/java/dev/steady/steady/controller/SteadyController.java
  src/main/java/dev/steady/steady/dto/request/SteadyQuestionUpdateRequest.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 📘 Documentation, ✏️ Feature, size/M

#102 [3차 스프린트 - Steady] 스테디 마감순 조회
  src/main/java/dev/steady/steady/domain/SteadyType.java
  src/main/java/dev/steady/steady/dto/SearchConditionDto.java
  src/main/java/dev/steady/steady/dto/request/SteadySearchRequest.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
  src/main/java/dev/steady/steady/infrastructure/util/DynamicQueryUtils.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImplTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 📘 Documentation, ✏️ Feature, 🧚 Refactor, size/L

#104 [3차 스프린트 - Steady] 피어 리뷰 기능 구현
  src/main/java/dev/steady/review/controller/ReviewController.java
  src/main/java/dev/steady/review/domain/Card.java
  src/main/java/dev/steady/review/domain/Review.java
  src/main/java/dev/steady/review/domain/UserCard.java
  src/main/java/dev/steady/review/domain/repository/CardRepository.java
  src/main/java/dev/steady/review/domain/repository/ReviewRepository.java
  src/main/java/dev/steady/review/domain/repository/UserCardRepository.java
  src/main/java/dev/steady/review/dto/ReviewCreateRequest.java
  src/main/java/dev/steady/review/exception/InvalidStateException.java
  src/main/java/dev/steady/review/exception/ReviewErrorCode.java
  src/main/java/dev/steady/review/service/ReviewService.java
  src/main/java/dev/steady/steady/domain/Participant.java
  src/main/java/dev/steady/steady/domain/Participants.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/repository/ParticipantRepository.java
  src/main/java/dev/steady/steady/exception/ParticipantErrorCode.java
  src/main/java/dev/steady/user/domain/User.java
  src/test/java/dev/steady/application/domain/repository/ApplicationRepositoryTest.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/review/fixture/ReviewFixtures.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: ✏️ Feature, size/XL

#108 [3차 스프린트 - User] 프로필 조회 및 수정 기능 구현
  src/main/java/dev/steady/auth/domain/repository/AccountRepository.java
  src/main/java/dev/steady/user/controller/UserController.java
  src/main/java/dev/steady/user/domain/User.java
  src/main/java/dev/steady/user/domain/repository/UserStackRepository.java
  src/main/java/dev/steady/user/dto/request/UserUpdateRequest.java
  src/main/java/dev/steady/user/dto/response/UserMyDetailResponse.java
  src/main/java/dev/steady/user/service/UserService.java
  src/test/java/dev/steady/auth/fixture/AccountFixture.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
  src/test/java/dev/steady/user/service/UserServiceTest.java
Labels: ✏️ Feature, size/L

#109 [3차 스프린트 - 스테디] 내 스테디 조회 API 개발
  src/main/java/dev/steady/review/exception/InvalidStateException.java
  src/main/java/dev/steady/steady/controller/SteadyController.java
  src/main/java/dev/steady/steady/dto/request/SteadyPageRequest.java
  src/main/java/dev/steady/steady/dto/response/MySteadyQueryResponse.java
  src/main/java/dev/steady/steady/dto/response/MySteadyResponse.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepository.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
  src/main/java/dev/steady/steady/infrastructure/util/DynamicQueryUtils.java
  src/main/java/dev/steady/steady/infrastructure/util/StringConverterUtils.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImplTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: size/L

#110 [4차 스프린트 - Steady] 누락된 코드 추가 및 리팩토링
  src/main/java/dev/steady/steady/controller/SteadyController.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/dto/response/PageResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadyQuestionsResponse.java
  src/main/java/dev/steady/steady/exception/SteadyErrorCode.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 📘 Documentation, ✏️ Feature, 🧚 Refactor, size/L

#113 [4차 스프린트 - 신청서] 신청서의 상태 변경에 따라 스테디 참여자에 추가
  src/main/java/dev/steady/application/controller/ApplicationController.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/main/java/dev/steady/steady/domain/Participant.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: size/M

#114 [3차 스프린트 - User] 타인의 프로필 조회 기능 구현
  src/main/java/dev/steady/global/exception/InvalidValueException.java
  src/main/java/dev/steady/review/domain/Review.java
  src/main/java/dev/steady/review/domain/repository/ReviewRepository.java
  src/main/java/dev/steady/review/domain/repository/UserCardRepository.java
  src/main/java/dev/steady/review/dto/response/UserCardResponse.java
  src/main/java/dev/steady/review/infrastructure/ReviewQueryRepository.java
  src/main/java/dev/steady/review/infrastructure/ReviewQueryRepositoryImpl.java
  src/main/java/dev/steady/review/infrastructure/UserCardQueryRepository.java
  src/main/java/dev/steady/review/infrastructure/UserCardQueryRepositoryImpl.java
  src/main/java/dev/steady/steady/dto/response/PageResponse.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/java/dev/steady/user/controller/UserController.java
  src/main/java/dev/steady/user/dto/request/UserCreateRequest.java
  src/main/java/dev/steady/user/dto/request/UserUpdateRequest.java
  src/main/java/dev/steady/user/dto/response/UserDetailResponse.java
  src/main/java/dev/steady/user/dto/response/UserOtherDetailResponse.java
  src/main/java/dev/steady/user/service/UserService.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImplTest.java
  src/test/java/dev/steady/user/controller/UserControllerTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
  src/test/java/dev/steady/user/service/UserServiceTest.java
Labels: ✏️ Feature, size/L

#118 [4차 스프린트 - 스테디] 스테디 질문 조회 API
  src/main/java/dev/steady/steady/dto/response/SteadyQuestionsResponse.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 🧚 Refactor, size/S

#119 [4차 스프린트 - Notification] 알림 기능 구현
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/main/java/dev/steady/notification/controller/NotificationController.java
  src/main/java/dev/steady/notification/domain/ApplicationResultNotificationStrategy.java
  src/main/java/dev/steady/notification/domain/FreshApplicationNotificationStrategy.java
  src/main/java/dev/steady/notification/domain/Notification.java
  src/main/java/dev/steady/notification/domain/NotificationMessage.java
  src/main/java/dev/steady/notification/domain/NotificationStrategy.java
  src/main/java/dev/steady/notification/domain/NotificationType.java
  src/main/java/dev/steady/notification/domain/repository/NotificationRepository.java
  src/main/java/dev/steady/notification/dto/NotificationResponse.java
  src/main/java/dev/steady/notification/dto/NotificationsResponse.java
  src/main/java/dev/steady/notification/exception/NotificationErrorCode.java
  src/main/java/dev/steady/notification/service/NotificationService.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/global/config/ControllerTestConfig.java
  src/test/java/dev/steady/notification/controller/NotificationControllerTest.java
  src/test/java/dev/steady/notification/fixture/NotificationFixture.java
  src/test/java/dev/steady/notification/service/NotificationServiceTest.java
Labels: 💢 Bug, 📘 Documentation, ✏️ Feature, size/XL

#120 [4차 스프린트 - Review] Review 가능 기간 검증 로직 추가
  src/main/java/dev/steady/review/domain/repository/ReviewRepository.java
  src/main/java/dev/steady/review/dto/ReviewCreateRequest.java
  src/main/java/dev/steady/review/exception/ReviewErrorCode.java
  src/main/java/dev/steady/review/service/ReviewService.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
Labels: 💢 Bug, ✏️ Feature, 🧚 Refactor, size/L

#122 [4차 스프린트 - 스테디] 스테디 상세조회할 때 조회수 증가
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/SteadyViewLog.java
  src/main/java/dev/steady/steady/domain/repository/ViewCountLogRepository.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadySearchResponse.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: ✏️ Feature, size/L

#124 [신청서] 신청서 목록 조회 반환값 추가
  src/main/java/dev/steady/application/dto/response/ApplicationSummaryResponse.java
  src/test/java/dev/steady/application/controller/ApplicationControllerTest.java
  src/test/java/dev/steady/application/fixture/ApplicationFixture.java
Labels: 📘 Documentation, 🧚 Refactor, size/S

#126 [4차 스프린트 - Steady] QueryDsl 페이징 버그 수정
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
Labels: 💢 Bug, size/S

#130 [4차 스프린트- User] User 프로필 조회, 수정 기능 Controller 테스트 및 문서화
  src/main/java/dev/steady/user/dto/response/UserDetailResponse.java
  src/main/java/dev/steady/user/dto/response/UserMyDetailResponse.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
  src/test/java/dev/steady/user/controller/UserControllerTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
Labels: 📘 Documentation, Test, 🧚 Refactor, size/L

#131 [4차 스프린트 - 좋아요] 스테디 게시물의 좋아요 기능 개발
  src/main/java/dev/steady/steady/controller/SteadyLikeController.java
  src/main/java/dev/steady/steady/domain/SteadyLike.java
  src/main/java/dev/steady/steady/domain/repository/SteadyLikeRepository.java
  src/main/java/dev/steady/steady/dto/response/SteadyLikeResponse.java
  src/main/java/dev/steady/steady/service/SteadyLikeService.java
  src/test/java/dev/steady/global/config/ControllerTestConfig.java
  src/test/java/dev/steady/steady/controller/SteadyLikeControllerTest.java
  src/test/java/dev/steady/steady/service/SteadyLikeServiceTest.java
Labels: size/L

#135 프로젝트 전체 예외 핸들링 [페어]
  src/main/java/dev/steady/auth/exception/OAuthPlatformException.java
  src/main/java/dev/steady/global/advice/GlobalExceptionHandler.java
  src/main/java/dev/steady/global/exception/AuthenticationException.java
  src/main/java/dev/steady/global/exception/BusinessException.java
  src/main/java/dev/steady/global/exception/ForbiddenException.java
  src/main/java/dev/steady/global/exception/GlobalErrorCode.java
  src/main/java/dev/steady/global/exception/InvalidStateException.java
  src/main/java/dev/steady/global/exception/InvalidValueException.java
  src/main/java/dev/steady/global/exception/NotFoundException.java
  src/main/java/dev/steady/global/response/ErrorResponse.java
Labels: ✏️ Feature, size/L

#132 [4차 스프린트 - Review] 내가 받은 리뷰 조회, 비공개 설정 기능 구현/Review 관련 Controller 테스트 및 문서화
  src/main/java/dev/steady/application/controller/ApplicationController.java
  src/main/java/dev/steady/global/config/QueryDslConfig.java
  src/main/java/dev/steady/notification/domain/ApplicationResultNotificationStrategy.java
  src/main/java/dev/steady/notification/domain/FreshApplicationNotificationStrategy.java
  src/main/java/dev/steady/notification/domain/NotificationMessage.java
  src/main/java/dev/steady/review/controller/ReviewController.java
  src/main/java/dev/steady/review/domain/Review.java
  src/main/java/dev/steady/review/domain/repository/ReviewRepository.java
  src/main/java/dev/steady/review/dto/request/ReviewCreateRequest.java
  src/main/java/dev/steady/review/dto/response/ReviewDetailResponse.java
  src/main/java/dev/steady/review/dto/response/ReviewMyResponse.java
  src/main/java/dev/steady/review/dto/response/ReviewSwitchResponse.java
  src/main/java/dev/steady/review/dto/response/ReviewsBySteadyResponse.java
  src/main/java/dev/steady/review/exception/ReviewErrorCode.java
  src/main/java/dev/steady/review/infrastructure/ReviewQueryRepository.java
  src/main/java/dev/steady/review/infrastructure/ReviewQueryRepositoryImpl.java
  src/main/java/dev/steady/review/infrastructure/UserCardQueryRepository.java
  src/main/java/dev/steady/review/infrastructure/UserCardQueryRepositoryImpl.java
  src/main/java/dev/steady/review/service/ReviewService.java
  src/main/java/dev/steady/user/service/UserService.java
  src/test/java/dev/steady/global/config/ControllerTestConfig.java
  src/test/java/dev/steady/review/controller/ReviewControllerTest.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/user/service/UserServiceTest.java
Labels: 📘 Documentation, Test, ✏️ Feature, size/L

#137 [5차 스프린트 - Steady] Bean Validation 적용
  src/main/java/dev/steady/steady/controller/SteadyController.java
  src/main/java/dev/steady/steady/dto/request/SteadyCreateRequest.java
  src/main/java/dev/steady/steady/dto/request/SteadyQuestionUpdateRequest.java
  src/main/java/dev/steady/steady/dto/request/SteadyUpdateRequest.java
Labels: ✏️ Feature, size/M

#140 [5차 스프린트 - Steady] 스테디 응답 객체에 좋아요 수 추가
  src/main/java/dev/steady/notification/domain/ApplicationResultNotificationStrategy.java
  src/main/java/dev/steady/notification/domain/FreshApplicationNotificationStrategy.java
  src/main/java/dev/steady/steady/controller/SteadyController.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/dto/response/SteadySearchResponse.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: 📘 Documentation, ✏️ Feature, 🧚 Refactor, size/L

#144 [신청서] 신청서, 질답 양방향 제거 및 대기 상태 신청서 답변 수정 기능 개발
  src/main/java/dev/steady/application/controller/ApplicationController.java
  src/main/java/dev/steady/application/domain/Application.java
  src/main/java/dev/steady/application/domain/SurveyResult.java
  src/main/java/dev/steady/application/domain/SurveyResults.java
  src/main/java/dev/steady/application/domain/repository/SurveyResultRepository.java
  src/main/java/dev/steady/application/dto/request/ApplicationUpdateAnswerRequest.java
  src/main/java/dev/steady/application/dto/response/ApplicationDetailResponse.java
  src/main/java/dev/steady/application/exception/SurveyResultErrorCode.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/test/java/dev/steady/application/controller/ApplicationControllerTest.java
  src/test/java/dev/steady/application/fixture/ApplicationFixture.java
  src/test/java/dev/steady/application/fixture/SurveyResultFixture.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
  src/test/java/dev/steady/notification/service/NotificationServiceTest.java
  src/test/java/dev/steady/template/service/TemplateServiceTest.java
  src/test/java/dev/steady/user/service/PositionServiceTest.java
  src/test/java/dev/steady/user/service/StackServiceTest.java
Labels: 📘 Documentation, ✏️ Feature, 🧚 Refactor, size/L

#147 [신청서] 내 신청서 조회 기능 개발
  src/main/java/dev/steady/application/controller/ApplicationController.java
  src/main/java/dev/steady/application/domain/repository/ApplicationRepository.java
  src/main/java/dev/steady/application/dto/response/MyApplicationSummaryResponse.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/test/java/dev/steady/application/controller/ApplicationControllerTest.java
  src/test/java/dev/steady/application/fixture/ApplicationFixture.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
Labels: ✏️ Feature, size/L

#142 [5차 스프린트 - User] 회원 탈퇴
  src/main/java/dev/steady/auth/domain/repository/AccountRepository.java
  src/main/java/dev/steady/review/domain/repository/ReviewRepository.java
  src/main/java/dev/steady/review/domain/repository/UserCardRepository.java
  src/main/java/dev/steady/review/service/ReviewService.java
  src/main/java/dev/steady/steady/domain/repository/ParticipantRepository.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/main/java/dev/steady/user/controller/UserController.java
  src/main/java/dev/steady/user/domain/User.java
  src/main/java/dev/steady/user/domain/WithdrawUserUtils.java
  src/main/java/dev/steady/user/dto/response/UserOtherDetailResponse.java
  src/main/java/dev/steady/user/service/UserService.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
  src/test/java/dev/steady/user/controller/UserControllerTest.java
  src/test/java/dev/steady/user/service/UserServiceTest.java
Labels: 📘 Documentation, ✏️ Feature, size/L

#151 [신청서] 신청서 작성자의 신청서 삭제 기능 개발
  src/main/java/dev/steady/application/controller/ApplicationController.java
  src/main/java/dev/steady/application/domain/Application.java
  src/main/java/dev/steady/application/domain/repository/SurveyResultRepository.java
  src/main/java/dev/steady/application/service/ApplicationService.java
  src/test/java/dev/steady/application/controller/ApplicationControllerTest.java
  src/test/java/dev/steady/application/service/ApplicationServiceTest.java
Labels: size/M

#154 스테디 핫픽스
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/SteadyPosition.java
  src/main/java/dev/steady/steady/dto/response/SteadyPositionResponse.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
Labels: 💢 Bug, 📝 Hot fix, size/XS

#152 [5차 스프린트 - Review] 리뷰 카드 조회 기능 수정
  src/main/java/dev/steady/review/domain/Card.java
  src/main/java/dev/steady/review/domain/Review.java
  src/main/java/dev/steady/review/dto/response/UserCardResponse.java
  src/main/java/dev/steady/review/infrastructure/ReviewQueryRepositoryImpl.java
  src/main/java/dev/steady/review/infrastructure/UserCardQueryRepositoryImpl.java
  src/main/java/dev/steady/review/service/ReviewService.java
  src/test/java/dev/steady/review/controller/ReviewControllerTest.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
  src/test/java/dev/steady/user/controller/UserControllerTest.java
Labels: 🧚 Refactor, size/M

#155 [5차 스프린트 - Steady] 스테디 리팩토링 및 버그 수정
  src/main/java/dev/steady/application/domain/repository/ApplicationRepository.java
  src/main/java/dev/steady/global/advice/GlobalExceptionHandler.java
  src/main/java/dev/steady/global/response/ErrorResponse.java
  src/main/java/dev/steady/notification/domain/Notification.java
  src/main/java/dev/steady/review/service/ReviewService.java
  src/main/java/dev/steady/steady/dto/response/SteadyDetailResponse.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/user/service/PositionServiceTest.java
  src/test/java/dev/steady/user/service/StackServiceTest.java
  src/test/java/dev/steady/user/service/UserServiceTest.java
Labels: 💢 Bug, 📘 Documentation, 🧚 Refactor, size/L

#157 [5차 스프린트 - Review] 리뷰 작성 페이지에 필요한 정보 제공 기능 구현
  src/main/java/dev/steady/review/controller/ReviewController.java
  src/main/java/dev/steady/review/dto/response/CardResponse.java
  src/main/java/dev/steady/review/dto/response/CardsResponse.java
  src/main/java/dev/steady/review/dto/response/ReviewInfoResponse.java
  src/main/java/dev/steady/review/dto/response/ReviewSteadyResponse.java
  src/main/java/dev/steady/review/dto/response/RevieweeResponse.java
  src/main/java/dev/steady/review/service/ReviewService.java
  src/test/java/dev/steady/review/controller/ReviewControllerTest.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
  src/test/java/dev/steady/review/service/ReviewServiceTest.java
Labels: 📘 Documentation, Test, ✏️ Feature, size/L

#162 [신청서] 내 신청서 조회 기능에 스테디 식별자 정보 추가
  src/main/java/dev/steady/application/dto/response/MyApplicationSummaryResponse.java
  src/test/java/dev/steady/application/controller/ApplicationControllerTest.java
  src/test/java/dev/steady/application/fixture/ApplicationFixture.java
Labels: size/XS

#161 스테디 필터링 검색 기능 좋아요 조건 추가
  src/main/java/dev/steady/steady/controller/SteadyController.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepository.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImplTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: ✏️ Feature, size/M

#164 [5차 스프린트 - Steady] 참여자 추방 기능
  src/main/java/dev/steady/steady/controller/SteadyController.java
  src/main/java/dev/steady/steady/domain/Participants.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/domain/repository/ParticipantRepository.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
Labels: ✏️ Feature, size/L

#165 [5차 스프린트] 프로필 이미지 업로드용 AWS S3 Presigned URL 제공 기능 수정
  src/main/java/dev/steady/storage/StorageService.java
  src/main/java/dev/steady/user/controller/UserController.java
  src/main/java/dev/steady/user/dto/response/ProfileUploadUrlResponse.java
  src/main/java/dev/steady/user/dto/response/PutObjectUrlResponse.java
  src/main/java/dev/steady/user/service/UserService.java
  src/test/java/dev/steady/user/controller/UserControllerTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
Labels: ✏️ Feature, size/M

#168 [6차 스프린트 - Steady] 연락 수단 추가
  src/main/java/dev/steady/notification/domain/ApplicationResultNotificationStrategy.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/dto/request/SteadyCreateRequest.java
  src/main/java/dev/steady/steady/dto/request/SteadyUpdateRequest.java
  src/main/java/dev/steady/steady/dto/response/MySteadyQueryResponse.java
  src/main/java/dev/steady/steady/dto/response/MySteadyResponse.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
  src/main/java/dev/steady/steady/service/SteadyService.java
  src/test/java/dev/steady/steady/controller/SteadyControllerTest.java
  src/test/java/dev/steady/steady/fixture/SteadyFixtures.java
Labels: 📘 Documentation, ✏️ Feature, size/M

#172 전체적인 코드 리팩토링
  src/main/java/dev/steady/global/config/QueryDslConfig.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/infrastructure/util/DynamicQueryUtils.java
  src/main/java/dev/steady/steady/infrastructure/util/StringConverterUtils.java
  src/main/java/dev/steady/template/domain/Questions.java
  src/main/java/dev/steady/user/domain/WithdrawUserUtils.java
  src/test/java/dev/steady/notification/service/NotificationServiceTest.java
  src/test/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImplTest.java
  src/test/java/dev/steady/steady/service/SteadyServiceTest.java
  src/test/java/dev/steady/user/fixture/UserFixtures.java
  src/test/java/dev/steady/user/service/PositionServiceTest.java
  src/test/java/dev/steady/user/service/StackServiceTest.java
Labels: 🧚 Refactor, size/M

#173 [6차 스프린트 - Review, Steady] Review의 steady 필드 제거 및 Participant soft delete 적용
  src/main/java/dev/steady/review/domain/Review.java
  src/main/java/dev/steady/review/domain/repository/ReviewRepository.java
  src/main/java/dev/steady/review/dto/request/ReviewCreateRequest.java
  src/main/java/dev/steady/review/infrastructure/ReviewQueryRepository.java
  src/main/java/dev/steady/review/infrastructure/ReviewQueryRepositoryImpl.java
  src/main/java/dev/steady/review/service/ReviewService.java
  src/main/java/dev/steady/steady/domain/Participant.java
  src/main/java/dev/steady/steady/domain/Participants.java
  src/main/java/dev/steady/steady/domain/Steady.java
  src/main/java/dev/steady/steady/infrastructure/SteadySearchRepositoryImpl.java
  src/test/java/dev/steady/review/fixture/ReviewFixture.java
Labels: 🧚 Refactor, size/M
